name: 非GKI内核构建工具

on:
  workflow_dispatch:
  
    inputs:
      CONFIG_FILE:
        description: '选择机型/版本'
        required: true
        default: 'oneplus9pro'
        type: choice
        options: 
        - 'oneplus9pro'

jobs:
  build:
    name: Build Kernel by ${{ github.actor }}
    runs-on: ubuntu-latest
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"
    steps:
    - uses: actions/checkout@v4
    - name: Prepare Configuration
      run: |
        CONFIG_ENV1=$(cat config-op9r.env | grep -w "CONFIG_ENV" | head -n 1 | cut -d "=" -f 2)
